addons:
    postgresql: "9.4"

services:
    - postgresql

language: python
python:
    - "2.7"
install: "python setup.py develop"

before_script:
    - createdb -O postgres -E UTF-8 thousands

script: "py.test"
deploy:
    provider: openshift
    user: "rush.ru@gmail.com"
    password: "5epsElIwMTqn"
    domain: "binrush"
    app: "thousandsdev"
